# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build specific pipeline branch

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    failOnThreshold: moderate  # Optional: moderate (default), low, high, critical
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    variableGroupName: ffc-pay-web-env-var
    pr_params:
      container.azureStorageCreateContainers: $(pr_azureStorageCreateContainers)
      container.azureStorageUseConnectionString: $(pr_azureStorageUseConnectionString)
      container.manualPaymentsActive: $(pr_manualPaymentsActive)
      container.azureAppRegistrationEnabled: $(pr_azureAppRegistrationEnabled)
      container.azureAppRegistrationClientId: $(pr_azureAppRegistrationClientId)
      container.azureAppRegistrationTenantId: $(pr_azureAppRegistrationTenantId)
      container.approvedEmailDomains: $(pr_approvedEmailDomains)
    snd2_params:
      container.azureStorageCreateContainers: $(snd2_azureStorageCreateContainers)
      container.azureStorageUseConnectionString: $(snd2_azureStorageUseConnectionString)
      container.manualPaymentsActive: $(snd2_manualPaymentsActive)
      container.azureAppRegistrationEnabled: $(snd2_azureAppRegistrationEnabled)
      container.azureAppRegistrationClientId: $(snd2_azureAppRegistrationClientId)
      container.azureAppRegistrationTenantId: $(snd2_azureAppRegistrationTenantId)
      container.approvedEmailDomains: $(snd2_approvedEmailDomains)
    dev_params:
      container.azureStorageCreateContainers: $(dev_azureStorageCreateContainers)
      container.azureStorageUseConnectionString: $(dev_azureStorageUseConnectionString)
      container.manualPaymentsActive: $(dev_manualPaymentsActive)
      container.azureAppRegistrationEnabled: $(dev_azureAppRegistrationEnabled)
      container.azureAppRegistrationClientId: $(dev_azureAppRegistrationClientId)
      container.azureAppRegistrationTenantId: $(dev_azureAppRegistrationTenantId)
      container.approvedEmailDomains: $(dev_approvedEmailDomains)
    test_params:
      container.azureStorageCreateContainers: $(test_azureStorageCreateContainers)
      container.azureStorageUseConnectionString: $(test_azureStorageUseConnectionString)
      container.manualPaymentsActive: $(test_manualPaymentsActive)
      container.azureAppRegistrationEnabled: $(test_azureAppRegistrationEnabled)
      container.azureAppRegistrationClientId: $(test_azureAppRegistrationClientId)
      container.azureAppRegistrationTenantId: $(test_azureAppRegistrationTenantId)
      container.approvedEmailDomains: $(test_approvedEmailDomains)
    pre_params:
      container.azureStorageCreateContainers: $(pre_azureStorageCreateContainers)
      container.azureStorageUseConnectionString: $(pre_azureStorageUseConnectionString)
      container.manualPaymentsActive: $(pre_manualPaymentsActive)
      container.azureAppRegistrationEnabled: $(pre_azureAppRegistrationEnabled)
      container.azureAppRegistrationClientId: $(pre_azureAppRegistrationClientId)
      container.azureAppRegistrationTenantId: $(pre_azureAppRegistrationTenantId)
      container.approvedEmailDomains: $(pre_approvedEmailDomains)
    prd_params:
      container.azureStorageCreateContainers: $(prd_azureStorageCreateContainers)
      container.azureStorageUseConnectionString: $(prd_azureStorageUseConnectionString)
      container.manualPaymentsActive: $(prd_manualPaymentsActive)
      container.azureAppRegistrationEnabled: $(prod_azureAppRegistrationEnabled)
      container.azureAppRegistrationClientId: $(prd_azureAppRegistrationClientId)
      container.azureAppRegistrationTenantId: $(prd_azureAppRegistrationTenantId)
      container.approvedEmailDomains: $(prd_approvedEmailDomains)
