# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-web:
    build:
      target: development
    image: ffc-pay-web-development
    container_name: ffc-pay-web-development
    depends_on:
      - ffc-pay-web-redis
    ports:
      - "3007:3007"
      - "9238:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      PAY_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-event-store-azurite:10000/devstoreaccount1;
      DOC_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-doc-statement-azurite:10000/devstoreaccount1;

  ffc-pay-web-redis:
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    command: redis-server --dir /data --save 5 1

  ffc-pay-event-store-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10070:10000"
      - "10071:10001"
      - "10072:10002"

volumes:
  azurite_data:
  redis_data:
