version: '3.8'

services:
  ffc-pay-web:
    build:
      context: .
      target: production
    image: ffc-pay-web
    container_name: ffc-pay-web
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      PAYMENTS_SERVICE_ENDPOINT: http://ffc-pay-processing:3008
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      SUBMISSION_TOPIC_ADDRESS: ${SUBMISSION_TOPIC_ADDRESS:-ffc-pay-submit}${MESSAGE_QUEUE_SUFFIX}
      SUBMISSION_SUBSCRIPTION_ADDRESS: ${SUBMISSION_SUBSCRIPTION_ADDRESS:-ffc-pay-submission}${MESSAGE_QUEUE_SUFFIX}
      PROCESSING_TOPIC_ADDRESS: ${PROCESSING_TOPIC_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      PROCESSING_SUBSCRIPTION_ADDRESS: ${PROCESSING_SUBSCRIPTION_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      ENRICHMENT_TOPIC_ADDRESS: ${ENRICHMENT_TOPIC_ADDRESS:-ffc-pay-request}${MESSAGE_QUEUE_SUFFIX}
      ENRICHMENT_SUBSCRIPTION_ADDRESS: ${ENRICHMENT_SUBSCRIPTION_ADDRESS:-ffc-pay-enrichment}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGE_TOPIC_ADDRESS: ${ACKNOWLEDGE_TOPIC_ADDRESS:-ffc-pay-acknowledge}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGE_SUBSCRIPTION_ADDRESS: ${ACKNOWLEDGE_SUBSCRIPTION_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      RETURN_TOPIC_ADDRESS: ${RETURN_TOPIC_ADDRESS:-ffc-pay-return}${MESSAGE_QUEUE_SUFFIX}
      RETURN_SUBSCRIPTION_ADDRESS: ${RETURN_SUBSCRIPTION_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"      
      AZURE_STORAGE_CREATE_CONTAINERS: "false"
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=https;AccountName=devffcpayst1001;AccountKey=yDjJYCYEXHoIt0YhdXR/fzIITj2KNRsXu33E708uARMNXrn2MNDAyJDrg9R+T3kBwv13GvG+Lxt7ET2DDOjq3g==;EndpointSuffix=core.windows.net}
