version: '3.8'

services:
  ffc-pay-web:
    build:
      context: .
      target: production
    image: ffc-pay-web
    container_name: ffc-pay-web
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      PAYMENTS_SERVICE_ENDPOINT: http://ffc-pay-processing:3008
      AZUREID_CLIENT_SECRET: ${AZUREID_CLIENT_SECRET}
      AZUREID_CLIENT_ID: ${AZUREID_CLIENT_ID}
      AZUREID_TENANT_ID: ${AZUREID_TENANT_ID}
      REDIRECT_URL: ${REDIRECT_URL}
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
