version: '3.8'

services:
  ffc-pay-web:
    depends_on: 
      - ffc-pay-web-azurite
    build:
      context: .
      target: production
    image: ffc-pay-web
    container_name: ffc-pay-web
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      PAYMENTS_SERVICE_ENDPOINT: http://ffc-pay-processing:3008
      DATA_HUB_SERVICE_ENDPOINT: http://ffc-pay-data-hub:3009
      AZUREID_CLIENT_SECRET: ${AZUREID_CLIENT_SECRET}
      AZUREID_CLIENT_ID: ${AZUREID_CLIENT_ID}
      AZUREID_TENANT_ID: ${AZUREID_TENANT_ID}
      REDIRECT_URL: ${REDIRECT_URL}
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      DATA_TOPIC_ADDRESS: ${DATA_TOPIC_ADDRESS:-ffc-pay-data-request}${MESSAGE_QUEUE_SUFFIX}
      DATA_QUEUE_ADDRESS: ${DATA_QUEUE_ADDRESS:-ffc-pay-data-request-response}${MESSAGE_QUEUE_SUFFIX}

  ffc-pay-web-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.17.1
    command: "azurite --blobHost 0.0.0.0 --tableHost 0.0.0.0 --loose"
