version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-payment-web:
    build:
      target: development
    image: ffc-sfi-payment-web-development
    container_name: ffc-sfi-payment-web-development
    ports:
      - "3007:3007"
      - "9238:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
