version: '3.8'

services:
  ffc-pay-web:
    build:
      context: .
      target: production
    image: ffc-pay-web
    container_name: ffc-pay-web
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      PAYMENTS_SERVICE_ENDPOINT: http://ffc-pay-processing:3008
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      REDIRECT_URL: ${REDIRECT_URL}
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"      
      AZURE_STORAGE_CREATE_CONTAINERS: "false"
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10016/devstoreaccount1}
