version: '3.8'

services:
  ffc-sfi-payment-web:
    build:
      context: .
      target: production
    image: ffc-sfi-payment-web
    container_name: ffc-sfi-payment-web
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-payment-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}      
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      PAYMENTS_SERVICE_ENDPOINT: http://ffc-sfi-payments:3008