environment: development
name: ffc-sfi-payment-web
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-payment-web

labels: web

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-processing-web-config-map

containerSecret:
  name: ffc-sfi-processing-web-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3007
  messageQueueHost: namespace.servicebus.windows.net

ingress:
  class: nginx
  endpoint: ffc-sfi-payment-web
  server: example.com

livenessProbe:
  path: /healthz
  port: 3007
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3007
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
