services:
  ffc-pay-web:
    build:
      target: development
    image: ffc-pay-web-development
    container_name: ffc-pay-web-development
    ports:
      - "3007:3007"
      - "9238:9229"
    volumes:
      - ../.gitignore:/workspaces:cached/.gitignore
      - ..:/workspaces:cached
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-event-store-azurite:10000/devstoreaccount1;TableEndpoint=http://ffc-pay-event-store-azurite:10002/devstoreaccount1;
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  
  ffc-pay-event-store-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10070:10000"
      - "10071:10001"
      - "10072:10002"

volumes:
  azurite_data:
