{{- include "ffc-helm-library.container-secret" (list . "ffc-pay-web.container-secret") -}}
{{- define "ffc-pay-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  {{- if .Values.azureAppRegistration.enabled }}
  AZURE_CLIENT_SECRET: {{ quote .Values.azureAppRegistration.clientSecret }}
  AZURE_CLIENT_ID: {{ quote .Values.azureAppRegistration.clientId }}
  AZURE_TENANT_ID: {{ quote .Values.azureAppRegistration.tenantId }}
  {{- end }}
{{- end -}}
