---
environment: production
environmentCode: prd
ingress:
  class: nginx
  endpoint: ffc-pay-web-prd
  server: azure.defra.cloud
container:
  paymentsEndpoint: http://ffc-pay-processing.ffc-pay
  trackingEndpoint: http://ffc-pay-tracking.ffc-pay
  injectionEndpoint: http://ffc-pay-injection.ffc-pay
  alertingEndpoint: http://ffc-pay-alerting.ffc-pay
  statementPublisherEndpoint: http://ffc-doc-statement-publisher.ffc-doc
  payEventStoreAzureStorageConnectionString: dummy
  payInjectionAzureStorageConnectionString: dummy
  docAzureStorageConnectionString: dummy
  azureStorageAccountName: prdffcpayst1001
  docAzureStorageAccountName: prdffcdocst1001
  messageQueueHost: PRDFFCINFSB1001.servicebus.windows.net
  dataTopicAddress: ffc-pay-data-request
  dataResponseQueueAddress: ffc-pay-data-request-response
  redisHostname: PRDFFCINFRD1001.redis.cache.windows.net
  redisPort: 6380
  stmtDbTimeoutMs: 2000
  stmtDbFailures: 3
  stmtDbResetMs: 10000
  azureAppRegistrationRedirectUrl: authenticate
secretProviderClass:
  azure:
    keyvaultName: PREFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appInsights-connectionString
        objectType: secret
      - objectName: prd-ffc-pay-cookie-password
        objectType: secret
      - objectName: prd-redisPassword
        objectType: secret
      - objectName: prd-ffcPayWebClientSecret
        objectType: secret

  secretObjects:
    - secretName: ffc-pay-web
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appInsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING
        - objectName: prd-ffc-pay-cookie-password
          key: COOKIE_PASSWORD
        - objectName: prd-redisPassword
          key: REDIS_PASSWORD
        - objectName: prd-ffcPayWebClientSecret
          key: AZUREID_CLIENT_SECRET