{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-payment-web.config-map") -}}
{{- define "ffc-sfi-payment-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.container.googleTagManagerKey }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey }}
  {{- end }}
  PAYMENTS_SERVICE_ENDPOINT: {{ quote .Values.container.paymentsEndpoint }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
{{- end -}}
